services:
  db:
    image: postgres:17
    container_name: testing-db
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=qwerty123"
      - "POSTGRES_DB=testing-db"
    ports:
      - "5430:5432"
    volumes:
      - "pg-data:/var/lib/postgresql"

volumes:
  pg-data: