services:
  db:
    image: postgres:17
    container_name: testing-db
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=qwerty123"
      - "POSTGRES_DB=testing-db"
    ports:
      - "5430:5432"
    volumes:
      - "pg-data:/var/lib/postgresql"

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"

  redis-insight:
    image: redis/redisinsight
    container_name: redis_insight-container
    ports:
      - "5540:5540"

volumes:
  pg-data: