spring:
  application:
    name: testing-project

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5430/testing-db
    username: postgres
    password: qwerty123

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

jwt.secret: KODE

# test
# test 2
# test 3
# test 4
